Add a search feature to the listCourtPage
Alexander-Schulte/Capstone-MyCourt pull request #21
Opened 2021-05-18 13:43 UTC by Alexander-Schulte

Hello again! :) Just a small PR, implemented a search feature to the listCourtPage. So now the user can filter by name and location to find his perfect court! :)
Thanks for your review! :)

2021-05-18 19:47 UTC, FriederikeM approved these changes
LGTM :) one mini comment 💃

2021-05-18 19:47 UTC, FriederikeM commented on src/components/ListCourtPage.js
> +  const [nameFilter, setNameFilter] = useState("");
Maybe now that you are filtering for both, the name and the location, you can rename this useState

2021-05-19 08:40 UTC, marwinburesch requested changes
Nice and concise :), good work 🐜 

Cheers 🍻

2021-05-19 08:40 UTC, marwinburesch commented on src/components/AddCourtPage.js
> +import { addItemToLocalStorage } from "../services/CourtStorage";
Would've expected this in another PR

2021-05-19 08:40 UTC, marwinburesch commented on src/components/CourtCard.js
> +      key={court.location}
Please consider using an `id` in the future, just to make sure it is unique. Maybe you'll have dumb users :)

2021-05-19 08:40 UTC, marwinburesch commented on src/components/ListCourtPage.js
> +      <div className="listHeaderWrapper">
Could be a `<header>`

2021-05-19 08:40 UTC, marwinburesch commented on src/components/ListCourtPage.js
> +      <div className="listContentWrapper">{renderCourt()}</div>
Could be a `<section>`, right?

2021-05-19 08:40 UTC, marwinburesch commented on src/components/Map.js
> +import { getItemsFromLocalStorage } from "../services/CourtStorage";
Is `Map.js` part of the search?

2021-05-19 09:21 UTC, merged