Added the basic Navigation to navigate between the four pages
Alexander-Schulte/Capstone-MyCourt pull request #5
Opened 2021-04-26 18:23 UTC by Alexander-Schulte

Hey guys! Just implemented my navbar for my app. I created my four "pages" so I can navigate between them. In my Navigation.js I implemented the link to the different pages when the user is clicking on one of the specific icons. The icons are svg from my adobe xd file! Thank u for your review! :)

2021-04-26 21:02 UTC, FriederikeM approved these changes
Looks mostly good, just two minor comments

2021-04-26 21:02 UTC, FriederikeM commented on src/components/Navigation.css
> +}
What does this refer to? I don't see anything with a class "LinkAnker" in your Navigation.js

2021-04-26 21:02 UTC, FriederikeM commented on src/images/MapIcon.svg
> +<svg id="MapIcon" data-name="Gruppe 44" xmlns="http://www.w3.org/2000/svg" width="39.794" height="34.351" viewBox="0 0 39.794 34.351">
I like that you are using your own SVGs, very cool! 😎

2021-04-26 21:03 UTC, soerendolling approved these changes
Just noticed something small. Everything else looks fine to me.

2021-04-26 21:03 UTC, soerendolling commented on src/App.css
> +  grid-template-rows: [header] 80px [main] auto [footer] 80px;
Looks like you are going from outside to inside with sorting. You might wann put the template-rows somewhere on the top as well

2021-04-26 22:23 UTC, hugh-burgess requested changes
Looks To Me Good!

2021-04-26 22:23 UTC, hugh-burgess commented on src/App.js
> +            <Route exact path="/">
if im not mistaken, i think the home one goes last, but check!

2021-04-27 06:55 UTC, namirsab commented on src/App.js
> +            <Route exact path="/">
Setting the order of the routes from more specific to more generic it's a good practice.
https://reactrouter.com/web/guides/primary-components/route-matchers

2021-04-27 06:59 UTC, namirsab approved these changes
Very good Alex!
Just a few comments, but nothing critical

2021-04-27 06:59 UTC, namirsab commented on src/App.css
> +  width: 100vw;
I'm not sure what you are trying to achieve, but I see that you've set the `max-width` in the app to `10vw` but here you are setting now the `Main` with to `100vw`.

2021-04-27 07:39 UTC, merged